#!/usr/bin/python
import settings
import argparse
import sys
import os

def get_argument_string():
    config_file = open(settings.openvpn_config_file, 'r')

    argument_string = ''
    for line in config_file:
        argument_string += ' --' + line.strip()

    return argument_string


def argument_parsing():
    """ Todo: add argument to enable server selection """
    parser = argparse.ArgumentParser(description='VPN server selection tool')

    parser.add_argument('-p', metavar='PROTOCOL',help='protocol',default=settings.default_protocol)
    parser.add_argument('-P', metavar='PORT',type=int,help='port',default=settings.default_port)

    args = parser.parse_args() 

    port = args.P
    protocol = args.p

    if protocol not in settings.protocol_ports:
        print("Invalid protocol: " + protocol)
        sys.exit()

    if port not in settings.protocol_ports[protocol]:
        print("Invalid port for " + protocol + ": " + str(port))
        sys.exit()

    return (protocol, port)


def main():
    (protocol, port) = argument_parsing()

    working_dir = os.path.dirname(os.path.realpath(__file__))

    server_id = 0
    server_id_map = {}
    for server in sorted(settings.servers.keys()):
        server_id += 1
        server_id_map[server_id] = server

        print(str(server_id) + " : " + server)

    server_option = int(input("Which one? ")) 

    server_address = settings.servers[server_id_map[server_option]]
    openvpn_server_address = ' --remote ' + server_address + ' ' + str(port)

    openvpn_protocol = ' --proto ' + protocol

    openvpn_command = 'clear && cd ' + working_dir + ' && sudo openvpn' + openvpn_protocol + openvpn_server_address + get_argument_string() 

    os.system(openvpn_command)


if __name__ == "__main__":
    main()
