#!/usr/bin/python
import argparse
import os
import sys

import settings


def get_argument_string():
    config_file = open(settings.openvpn_config_file, 'r')

    argument_string = ''
    for line in config_file:
        argument_string += ' --{0}'.format(line.strip())

    return argument_string


def argument_parsing():
    parser = argparse.ArgumentParser(description='VPN server selection tool')

    parser.add_argument('-p',
                        metavar='PROTOCOL',
                        help='protocol',
                        default=settings.default_protocol)
    parser.add_argument('-P',
                        metavar='PORT',
                        type=int,
                        help='port',
                        default=settings.default_port)

    args = parser.parse_args()

    port = args.P
    protocol = args.p

    if protocol not in settings.protocol_ports:
        print('Invalid protocol: {0}'.format(protocol))
        sys.exit()

    if port not in settings.protocol_ports[protocol]:
        print('Invalid port for {0}: {1}'.format(protocol, port))
        sys.exit()

    return (protocol, port)


def main():
    (protocol, port) = argument_parsing()

    server_id_map = {}
    for server_id, server in enumerate(sorted(settings.servers), start=1):
        server_id_map[server_id] = server

        print('{0} : {1}'.format(server_id, server))

    server_option = int(input("Which one? "))

    server_address = settings.servers[server_id_map[server_option]]

    working_dir = os.path.dirname(os.path.realpath(__file__))

    pre_command = 'clear && cd {0}'.format(working_dir)
    os.system(pre_command)

    openvpn_command = ('sudo openvpn --proto {protocol}'
                       ' --remote {server} {port}'
                       ' {additional_args}'
                       ''.format(protocol=protocol,
                                 server=server_address,
                                 port=port,
                                 additional_args=get_argument_string()))

    print(openvpn_command)
    os.system(openvpn_command)


if __name__ == "__main__":
    main()
